### ISSUE TITLE
ModuleNotFoundError: No module named 'network_models'

### ISSUE THREAD

**Issue by xuwanlu** [microsoft/Semantics-Aligned-Representation-Learning-for-Person-Re-identification#2]
I meet error :ModuleNotFoundError: No module named 'network_models,
so I can't load the 'pkl model, can you update the file ? or can you give me some advice?

**Comment by wencoast** [comment]
@xuwanlu Have you solved this problem, I meet the same problem.

**Comment by jinx-USTC** [comment]
which step you meet this problem????

**Comment by wencoast** [comment]
@jinx-USTC 

More details can be found as follows,

/project/snow_datasets/Re_ID_datasets/model_weights/texture_generation_weights/texture_generation_weights.pkl
Traceback (most recent call last):
  File "/home/p283369/PaperWork/CASIA_Work/semantic_alignment_re_id_own_project/SemanticAlignmentReID/generate_texture_backup.py", line 55, in <module>
    generator = Generate_texture(model_path)
  File "/home/p283369/PaperWork/CASIA_Work/semantic_alignment_re_id_own_project/SemanticAlignmentReID/generate_texture_backup.py", line 17, in __init__
    self.model = torch.load(model_path, map_location='cpu') #0.4.1版本的pytorch也不行
  File "/home/p283369/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/p283369/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'network_models'

**Comment by jinx-USTC** [comment]
Sorry, I didn't meet this problem, and maybe you can refer to this link to find solution: https://github.com/microsoft/MMdnn/issues/572

**Comment by jszgz** [comment]
python generate_texture.py -m /DOWNLOADED_SAN-PG_WEIGHTS -i example_results/input -o example_results/texture

When running this, I met this problem, too. @xuwanlu Have you solved this problem?

**Comment by jszgz** [comment]
If I create a directory named "network_models" , then the error became
`ModuleNotFoundError: No module named 'network_models.unet'`
If I create a python file in `network_models` named 'unet' , then the error became
`Can't get attribute 'UNet' on <module 'network_models.unet'`
If I create UNet class in file `network_models/unet.py`, then the error became
`type object 'UNet' has no attribute 'dump_patches'`
If I Inheritance torch.nn.Module , then the error became
`Can't get attribute 'UNet_' on <module 'network_models.unet'`

Anyway, I can't use the pkl file you provide to Generate Pseudo Groundtruth Texture Images, and can you explain why did you use UNet while you saied you 'reuse the proposed SAN-PG'.

**Comment by jszgz** [comment]
[TextureGeneration](https://github.com/yt4766269/TextureGeneration)

`network_models` are in another repo, copy those to this repo so you can run generate_texture.py

So,  the author use Another Repo to Generate Pseudo Groundtruth Texture Images or did use SAN-PG as in the paper?
 @jinx-USTC

**Comment by jszgz** [comment]
![HASH](https://i.loli.net/2020/07/17/sBeiKjH5qJN9m3v.png)
The pre-trained weight for SAN-PG and pretrained weight in yt4766269/TextureGeneration have same SHA1-HASH CODE?

**Comment by wencoast** [comment]
@jszgz @jinx-USTC Could you send one email to my email address? May I ask you something about this project? My email address is codingprogram@outlook.com.
