### ISSUE TITLE
OSError: /MyDataDirectory/data/cuhk03/images_labeled/3_068_1_01.png does not exist

### ISSUE THREAD

**Issue by wencoast** [microsoft/Semantics-Aligned-Representation-Learning-for-Person-Re-identification#3]
I strictly follow your README file step by step. 

The code is runnable, but I always get this error after several batches.

The details for this error can be described as follows. 

Could you please tell me how to fix this error? 

Traceback (most recent call last):
  File "/home/p283369/PaperWork/CASIA_Work/semantic_alignment_re_id_own_project/SemanticAlignmentReID/main.py", line 543, in <module>
    main()
  File "/home/p283369/PaperWork/CASIA_Work/semantic_alignment_re_id_own_project/SemanticAlignmentReID/main.py", line 306, in main
    train(epoch, model, model_decoder, criterion_xent, criterion_htri, optimizer_warmup, optimizer_decoder, optimizer_encoder, trainloader, use_gpu)
  File "/home/p283369/PaperWork/CASIA_Work/semantic_alignment_re_id_own_project/SemanticAlignmentReID/main.py", line 366, in train
    for batch_idx, (imgs, pids, _, img_paths, imgs_texture) in enumerate(trainloader):
  File "/home/p283369/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/p283369/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OSError: Traceback (most recent call last):
  File "/home/p283369/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/p283369/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/p283369/PaperWork/CASIA_Work/semantic_alignment_re_id_own_project/SemanticAlignmentReID/torchreid/dataset_loader.py", line 44, in __getitem__
    img = read_image(img_path)
  File "/home/p283369/PaperWork/CASIA_Work/semantic_alignment_re_id_own_project/SemanticAlignmentReID/torchreid/dataset_loader.py", line 20, in read_image
    raise IOError("{} does not exist".format(img_path))
OSError: /project/snow_datasets/Re_ID_datasets/data/cuhk03/images_labeled/3_068_1_01.png does not exist

Process finished with exit code 1

**Comment by wencoast** [comment]
@lcl-2019

**Comment by wencoast** [comment]
This problem can be solved by changing the split style.
